/*
 * Copyright March - 2019
 * JTK POLBAN.
 * Made in Ciwaruga.
 */
package View;

/**
 *
 * @author ASUS
 */
public class ATMFrame extends javax.swing.JFrame {

    private final KeypadAdapter keyAdapter = new KeypadAdapter();
    private final OuterKeypadAdapter outerPadAdapter = new OuterKeypadAdapter();
    private final ATMScreen atmScreen = new ATMScreen();
    private final ATMKeypad atmKeypad = new ATMKeypad(getKeyAdapter());
    private final ATMDispense atmDispense = new ATMDispense();
    private final ATMOuterKeypad atmOuterKeypad = new ATMOuterKeypad(getOuterPadAdapter());

    /**
     * Creates new form ATMFrame
     *
     * @param adapter
     */
    public ATMFrame() {
        initialize();
        keyAdapter.addObserver(atmScreen);
    }

    private void initialize() {
        initComponents();
        screenPanel.add(getAtmScreen());
        screenPanel.repaint();
        keypadPanel.add(getAtmKeypad());
        keypadPanel.repaint();
        dispensePanel.add(getAtmDispense());
        dispensePanel.repaint();
        OuterKeypadPanel.add(atmOuterKeypad);
        OuterKeypadPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        keypadPanel = new javax.swing.JPanel();
        dispensePanel = new javax.swing.JPanel();
        screenPanel = new javax.swing.JPanel();
        OuterKeypadPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(660, 670));
        setMinimumSize(new java.awt.Dimension(660, 670));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(660, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1030, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(660, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 190, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 250, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 190, 250));

        keypadPanel.setBackground(new java.awt.Color(255, 255, 255));
        keypadPanel.setLayout(new java.awt.CardLayout());
        jPanel3.add(keypadPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 350, 250));

        dispensePanel.setBackground(new java.awt.Color(255, 255, 255));
        dispensePanel.setLayout(new java.awt.CardLayout());
        jPanel3.add(dispensePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 560, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 600, 310));

        screenPanel.setBackground(new java.awt.Color(255, 255, 255));
        screenPanel.setLayout(new java.awt.CardLayout());
        jPanel1.add(screenPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 440, 300));
        screenPanel.getAccessibleContext().setAccessibleName("screenPanel");

        OuterKeypadPanel.setBackground(new java.awt.Color(153, 153, 153));
        OuterKeypadPanel.setMinimumSize(new java.awt.Dimension(990, 440));
        OuterKeypadPanel.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(OuterKeypadPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 620, 320));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 620, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 620, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OuterKeypadPanel;
    private javax.swing.JPanel dispensePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel keypadPanel;
    private javax.swing.JPanel screenPanel;
    // End of variables declaration//GEN-END:variables


    public ATMScreen getAtmScreen() {
        return atmScreen;
    }

    public ATMKeypad getAtmKeypad() {
        return atmKeypad;
    }

    public ATMDispense getAtmDispense() {
        return atmDispense;
    }

    public KeypadAdapter getKeyAdapter() {
        return keyAdapter;
    }

    public OuterKeypadAdapter getOuterPadAdapter() {
        return outerPadAdapter;
    }
}
